### ISSUE TITLE
No data found

### ISSUE THREAD

**Issue by ahumblenerd** [naveen-iyer-13/cryptocurrency-tracker#1]
Hello Naveen,

I tried running the solution but it shows no data found.

Regards,
Arun Purushothaman
<img width="1440" alt="screen shot 2018-02-17 at 1 46 14 am" src="https://user-images.githubusercontent.com/9018661/36327613-1203117a-1385-11e8-9752-346b0db2cad0.png">

**Comment by ahumblenerd** [comment]
Fixed it by adding 

`  componentDidMount() { `
`    this.props.getData();`
`   setInterval(() => this.props.getData(), 30000)`
`  } `


inside List.js. Causes the method to be called instantly.

**Comment by naveen-iyer-13** [comment]
@ahumblenerd This is already present in the code. I had already pushed it.
